# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0002_auto_20151210_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', '男'), ('FEMALE', '女')], max_length=10, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('percentile', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='百分位')),
                ('original_score_20m', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='20米跑')),
                ('original_score_bal', models.IntegerField(verbose_name='后退平衡')),
                ('original_score_shh', models.IntegerField(verbose_name='侧向跳')),
                ('original_score_rb', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='立位体前屈')),
                ('original_score_ls', models.IntegerField(verbose_name='俯卧撑')),
                ('original_score_su', models.IntegerField(verbose_name='仰卧起坐')),
                ('original_score_sws', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='立定跳远')),
                ('original_score_ball', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='投掷球')),
                ('original_score_lauf', models.IntegerField(verbose_name='6分钟跑')),
            ],
        ),
    ]
