# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsman', '0010_auto_20160217_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_20m',
            new_name='e_20m',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_bal',
            new_name='e_bal',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_ball',
            new_name='e_ball',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_lauf',
            new_name='e_lauf',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_ls',
            new_name='e_ls',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_rb',
            new_name='e_rb',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_shh',
            new_name='e_shh',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_su',
            new_name='e_su',
        ),
        migrations.RenameField(
            model_name='standardparameter',
            old_name='original_score_sws',
            new_name='e_sws',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_20m',
            new_name='e_20m',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_bal',
            new_name='e_bal',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_ball',
            new_name='e_ball',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_lauf',
            new_name='e_lauf',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_ls',
            new_name='e_ls',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_rb',
            new_name='e_rb',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_shh',
            new_name='e_shh',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_su',
            new_name='e_su',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='original_score_sws',
            new_name='e_sws',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_20m',
            new_name='p_20m',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_bal',
            new_name='p_bal',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_ball',
            new_name='p_ball',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_lauf',
            new_name='p_lauf',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_ls',
            new_name='p_ls',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_rb',
            new_name='p_rb',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_shh',
            new_name='p_shh',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_su',
            new_name='p_su',
        ),
        migrations.RenameField(
            model_name='studentevaluation',
            old_name='percentage_sws',
            new_name='p_sws',
        ),
    ]
